#!/bin/bash
PS3="Choose a desktop environment: "
select opt in kde minimal; do
    case $opt in
    kde)
        echo "Installing KDE...."
        sudo pacman -Syyu plasma kde-applications networkmanager sddm xorg  --noconfirm
        break;
        ;;
    minimal)
        echo "Not installing any desktop environment"
        echo "You may want to configure wifi using arch-root since NetworkManager will not be installed"
        echo "Use dhcpcd & wpa_supplicant"
        break;
        ;;
    *)
        echo "Option not recognized....no DE to be installed"
        break;
        ;;
    esac
done